package in.patrickmart.model.forces;

import in.patrickmart.model.Entity;
import in.patrickmart.model.Vector2D;

import java.util.ArrayList;

public abstract class Force {
    protected Vector2D position;
    protected Vector2D force;

    //Store the source and destination entities in order to provide data for our calculate methods.
    protected Entity source;
    protected Entity destination;

    /**
     * Constructor for objects of class Force. Implements template method pattern to allow concrete forces to calculate
     * their effects separately from the way those effects are applied.
     * @param source The Entity that is generating this force
     * @param destination The Entity that this force is being applied to.
     */
    public Force(Entity source, Entity destination) {
        this.source = source;
        this.destination = destination;

        position = calculatePosition();
        force = calculateDirection();
        force.setMag(calculateNewtons());
        applyTo(destination);
    }

    /**
     * Constructor for objects of class Force which have multiple destinations. In order to apply a single force to
     * many destinations, we generate a generic force to apply to each of those destinations.
     * @param source An entity that has generated this force. May be null (Such as when generated by Scenarios)
     * @param destinations A list of entities that this force applies to.
     */
    public Force(Entity source, ArrayList<Entity> destinations) {
        this.source = source;

        for (Entity destination : destinations) {
            this.destination = destination;
            position = calculatePosition();
            force = calculateDirection();
            force.setMag(calculateNewtons());

            // Rather than use applyTo, we create a singular Force, whose constructor uses applyTo.
            new ForceGeneric(source, destination, force, position);
        }
    }

    /**
     * Constructor for objects of class force which will define their data on their own. This is dangerous and should
     * not be used unless necessary.
     */
    public Force() {

    }

    /**
     * Where does this force interact with its destination from?
     */
    abstract Vector2D calculatePosition();

    /**
     * What direction is this force being applied in?
     */
    abstract Vector2D calculateDirection();

    /**
     * How much force is being applied?
     */
    abstract double calculateNewtons();

    /**
     * Add this force to an entity's net force calculation.
     * @param destination the entity
     */
    protected void applyTo(Entity destination) {
        destination.applyForce(this);
    }

    /**
     * Accessor for this force as a vector.
     * @return This force as a positionless vector.
     */
    public Vector2D getForce() {
        return force;
    }

    /**
     * Accessor for the position of this force.
     * @return This force's position in the scenario.
     */
    public Vector2D getPosition() {
        return position;
    }
}
